#!/usr/bin/env python3
"""
Extract blocked and directionally-restricted tile IDs from Tuxemon .tsx files.

Tiles are considered blocked if:
  - enter_from="" (fully blocked from all directions)
  - surfable property exists (water tiles, impassable on foot)

Tiles with partial enter_from/exit_from (not empty, not all 4 directions)
are exported as directional restrictions.

Output: src/game/data/blockedTiles.ts
"""

import json
import os
import sys
import xml.etree.ElementTree as ET

TILESETS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "mods", "tuxemon", "gfx", "tilesets"
)
OUTPUT_FILE = os.path.join(
    os.path.dirname(__file__), "..", "src", "game", "data", "blockedTiles.ts"
)

ALL_DIRS = {"up", "down", "left", "right"}


def parse_directions(val: str) -> set[str]:
    """Parse a comma-separated direction string like 'up,left,right'."""
    return {d.strip() for d in val.split(",") if d.strip()}


def extract_tiles() -> tuple[
    dict[str, list[int]],
    dict[str, dict[str, dict[str, list[str]]]],
]:
    """Returns (fully_blocked, directional).

    directional maps tileset name -> { tileId -> { enter_from?: [...], exit_from?: [...] } }
    Only includes tiles with partial restrictions (not fully blocked, not fully open).
    """
    blocked_result: dict[str, list[int]] = {}
    dir_result: dict[str, dict[str, dict[str, list[str]]]] = {}

    for fname in sorted(os.listdir(TILESETS_DIR)):
        if not fname.endswith(".tsx"):
            continue
        tree = ET.parse(os.path.join(TILESETS_DIR, fname))
        root = tree.getroot()
        name = root.get("name")
        if name is None:
            continue

        blocked_ids: set[int] = set()
        dir_tiles: dict[str, dict[str, list[str]]] = {}

        for tile in root.findall("tile"):
            tid_str = tile.get("id")
            if tid_str is None:
                continue
            tid = int(tid_str)

            props: dict[str, str] = {}
            for prop in tile.findall("properties/property"):
                pname = prop.get("name", "")
                pval = prop.get("value", "")
                props[pname] = pval

            # Fully blocked
            if props.get("enter_from") == "":
                blocked_ids.add(tid)
                continue
            if "surfable" in props:
                blocked_ids.add(tid)
                continue

            # Directional restrictions
            tile_dirs: dict[str, list[str]] = {}
            for key in ("enter_from", "exit_from"):
                if key in props:
                    dirs = parse_directions(props[key])
                    if dirs and dirs != ALL_DIRS:
                        tile_dirs[key] = sorted(dirs)

            if tile_dirs:
                dir_tiles[str(tid)] = tile_dirs

        if blocked_ids:
            blocked_result[name] = sorted(blocked_ids)
        if dir_tiles:
            dir_result[name] = dir_tiles

    return blocked_result, dir_result


def main() -> None:
    blocked, directional = extract_tiles()

    lines = [
        "/**",
        " * Blocked and directionally-restricted tile IDs per tileset,",
        " * extracted from Tuxemon .tsx files.",
        " * Generated by scripts/generate-blocked-tiles.py — do not edit manually.",
        " */",
        "",
        "// prettier-ignore",
        "const RAW: Record<string, number[]> = " + json.dumps(blocked) + ";",
        "",
        "const blockedTileSets: Map<string, Set<number>> = new Map(",
        '  Object.entries(RAW).map(([name, ids]) => [name, new Set(ids)]),',
        ");",
        "",
        "export default blockedTileSets;",
        "",
        "export type AllowedDirs = { enter_from?: string[]; exit_from?: string[] };",
        "",
        "// prettier-ignore",
        "const DIR_RAW: Record<string, Record<string, AllowedDirs>> = " + json.dumps(directional) + ";",
        "",
        "/** Map from tileset name to Map<localTileId, AllowedDirs>. */",
        "export const directionalTileSets: Map<string, Map<number, AllowedDirs>> = new Map(",
        "  Object.entries(DIR_RAW).map(([name, tiles]) => [",
        "    name,",
        "    new Map(Object.entries(tiles).map(([id, dirs]) => [Number(id), dirs])),",
        "  ]),",
        ");",
        "",
    ]

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))

    total_blocked = sum(len(v) for v in blocked.values())
    total_dir = sum(len(v) for v in directional.values())
    print(f"Generated {OUTPUT_FILE}")
    print(f"  {len(blocked)} tilesets, {total_blocked} fully-blocked tile IDs")
    print(f"  {len(directional)} tilesets, {total_dir} directionally-restricted tile IDs")
    for name in sorted(set(list(blocked.keys()) + list(directional.keys()))):
        b = len(blocked.get(name, []))
        d = len(directional.get(name, {}))
        print(f"  {name}: {b} blocked, {d} directional")


if __name__ == "__main__":
    main()
