#!/usr/bin/env python3
"""
Extract blocked tile IDs from Tuxemon .tsx tileset files.

Tiles are considered blocked if:
  - enter_from="" (fully blocked from all directions)
  - surfable property exists (water tiles, impassable on foot)

Output: src/game/data/blockedTiles.ts
"""

import json
import os
import sys
import xml.etree.ElementTree as ET

TILESETS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "mods", "tuxemon", "gfx", "tilesets"
)
OUTPUT_FILE = os.path.join(
    os.path.dirname(__file__), "..", "src", "game", "data", "blockedTiles.ts"
)


def extract_blocked_tiles() -> dict[str, list[int]]:
    result: dict[str, list[int]] = {}

    for fname in sorted(os.listdir(TILESETS_DIR)):
        if not fname.endswith(".tsx"):
            continue
        tree = ET.parse(os.path.join(TILESETS_DIR, fname))
        root = tree.getroot()
        name = root.get("name")
        if name is None:
            continue

        blocked_ids: set[int] = set()

        for tile in root.findall("tile"):
            tid_str = tile.get("id")
            if tid_str is None:
                continue
            tid = int(tid_str)
            for prop in tile.findall("properties/property"):
                pname = prop.get("name", "")
                pval = prop.get("value", "")
                if pname == "enter_from" and pval == "":
                    blocked_ids.add(tid)
                if pname == "surfable":
                    blocked_ids.add(tid)

        if blocked_ids:
            result[name] = sorted(blocked_ids)

    return result


def main() -> None:
    data = extract_blocked_tiles()

    lines = [
        "/**",
        " * Blocked tile local IDs per tileset, extracted from Tuxemon .tsx files.",
        " * Tiles with enter_from='' (fully blocked) or surfable (water).",
        " * Generated by scripts/generate-blocked-tiles.py — do not edit manually.",
        " */",
        "",
        "// prettier-ignore",
        "const RAW: Record<string, number[]> = " + json.dumps(data) + ";",
        "",
        "const blockedTileSets: Map<string, Set<number>> = new Map(",
        '  Object.entries(RAW).map(([name, ids]) => [name, new Set(ids)]),',
        ");",
        "",
        "export default blockedTileSets;",
        "",
    ]

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))

    total = sum(len(v) for v in data.values())
    print(f"Generated {OUTPUT_FILE}")
    print(f"  {len(data)} tilesets, {total} blocked tile IDs total")
    for name, ids in data.items():
        print(f"  {name}: {len(ids)} blocked tiles")


if __name__ == "__main__":
    main()
